### ISSUE TITLE
[DOCS] (#22482)  Deprecate normalize parameter in `calibration_curve`

### ISSUE THREAD

**Issue by tapasrastogi2411** [navn-r/scikit-learn#10]
Investigate what parts of the existing code base you would need to modify in order to implement this bug fix. 

- [x]  Write documentation, explaining the issue and what your intended solution is 

- [x] Produce designs for the selected bug fix, describing your plans for the organization of new code, as well as all interactions between new code and existing code, through a UML/Sequence diagram

**Comment by navn-r** [comment]
Completed
