### ISSUE TITLE
Structuring and documenting our development process

### ISSUE THREAD

**Issue by divyam-p** [navn-r/scikit-learn#5]

**Comment by navn-r** [comment]
Original Document: https://docs.google.com/document/d/1ExQPqpexUHCscw1PJCCsBmYDllCvfONEMIB6gFduxII/edit

Final page: https://cscd01.netlify.app/a2/process/

Linked Commit: https://github.com/UTSCCSCD01/course-project-unbounded/commit/aa9b1907695d0b0c2cb5f048429a2825e93c95ef

Closing this issue, as it has been completed.
